# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjdkYmRhNDg0Y2U3MTZjNWExMGRkNmZmM2NlODg5OWY2ZTkxYjBlMDcyZWM1N2MxNWI5YjQxZGEwNDIwMDNkNDlhMjBmYTMzYjU1NDVlZTc1NjIxYTEyZjVjNzJmMWY0YjFjNjQ3YmQxZjk3MjdjNWJlYjEzZTYwYzVhMDAwMmE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
